feat(SignUp): Login Form
atlp-rwanda/phantom-fe-dream-team pull request #14
Opened 2022-05-01 19:39 UTC by Juleshb

#### What does this PR do?

As a driver or an operator, I want to be able to login with credentials provided in my email, so that I can perform my tasks. For a better UX, show the login page views using UI skeletons when the page is loading.

#### Description of Task to be completed?

-Appropriate error messages are displayed on invalid inputs (Form validation).
-The page is responsive.
-Appropriate error messages are displayed on unsuccessful attempts

How should this be manually tested?
-clone repo
-run npm install
-git checkout ft-signIn-#29
-npm run dev:start
Routes:
-To reset password: http://localhost:3000

Any background context you want to provide?
-N/A

What are the relevant pivotal tracker stories?
-Link:https://trello.com/c/MT1mxlVg

Screenshots (if appropriate)

![Screen Shot 2022-04-28 at 22 40 13](https://user-images.githubusercontent.com/93904693/166161870-06de71d8-03cf-4520-8e01-566fd2cbea06.png)
<img width="1440" alt="Screen Shot 2022-04-28 at 22 43 59" src="https://user-images.githubusercontent.com/93904693/166161877-50f1fee6-963d-4b93-af74-d7c2b3af0a63.png">

2022-05-01 21:48 UTC, songa1 reviewed
Your file name should be sign in, not sign up. 
And your page doesn't have a footer. 
Your buttons are also different from what was expected from the mockups.

Lastly, put your feature on `/login` or `/signin`

2022-05-02 14:14 UTC, arthurjunior250 commented
I can't find your reducer and action

2022-05-02 14:24 UTC, arthurjunior250 requested changes
add your reducer and action

2022-05-18 12:21 UTC, songa1 approved these changes

2022-05-18 12:26 UTC, shemalucien approved these changes

2022-05-18 13:57 UTC, arthurjunior250 approved these changes

2022-05-18 14:00 UTC, Stevenkwizera06 approved these changes

2022-05-18 15:35 UTC, merged