#27 chore:configure testing environment
atlp-rwanda/phantom-fe-dream-team pull request #2
Opened 2022-04-05 15:27 UTC by arthurjunior250

**What does this PR do?**

-Configured Testing environment with Jest & Enzyme

** Description of Task to be completed?**

-All functionalities are tested before deployment.

**#### How should this be manually tested?**

-Clone the repo

-checkout to branch ch-setup-testing-#27

--Run npm run test

#### What are the relevant pivotal tracker **stories?**

-link to my pivotal tracker/tello/https://trello.com/c/wrRkUEwa

**#### Screenshots (if appropriate)**

![Screenshot from 2022-04-05 17-26-27](https://user-images.githubusercontent.com/46368773/161789527-063f9432-2cde-44b2-affe-27a7aa85cc5d.png)

**#### Questions:**
-N/A

2022-04-05 17:24 UTC, shemalucien commented
Good job mn I think you can add dodo, achile, and other team members as if you did not add them to review your PR.

2022-04-05 19:01 UTC, harerajo submitted a review, later dismissed

2022-04-06 08:13 UTC, mukunzidd requested changes
Fix the coverage script and the PR will be ready to be merged.

2022-04-06 08:13 UTC, mukunzidd commented on src/App.test.js
> +  render(<App />);
The coverage script is failing at this line. Check what's wrong.

2022-04-06 08:13 UTC, mukunzidd commented on src/App.test.js
> +  render(<App />);
The coverage script is failing at this line. Check what's wrong.

2022-04-06 09:28 UTC, Stevenkwizera06 approved these changes, later dismissed

2022-04-06 12:58 UTC, songa1 reviewed
Please check out feedbacks given by @Dodo and solve the problems in your script and in index.js file.

2022-04-08 11:30 UTC, songa1 submitted a review, later dismissed
Tests written are passing. And the environment is set and ready.

2022-04-15 17:38 UTC, songa1 approved these changes

2022-04-15 17:55 UTC, Stevenkwizera06 approved these changes

2022-04-17 07:22 UTC, shemalucien approved these changes

2022-04-17 11:56 UTC, harerajo approved these changes

2022-04-17 17:12 UTC, Juleshb approved these changes

2022-04-19 08:15 UTC, merged