Ft crud operation for buses #33
atlp-rwanda/phantom-fe-dream-team pull request #32
Opened 2022-05-23 10:37 UTC by arthurjunior250

**What does this PR do?**

Implements Crud operations for buses.

**Description of Task to be completed?**

-The operator should be able to create, update, and delete a bus.
-The operator should be able to view a paginated list of buses in the system.
-Users should be able to view the bus's details.
-Skeleton UIs/screen are/is shown when the page loads/is loading.
-The page is responsive.
-The page is responsive.

**How should this be manually tested?**

Clone the repo

checkout to branch `Ft-Crud-Operation-for-Buses-#33`

Run npm install to install modules

Run npm run `dev:start ` to start the development server

What are the relevant Pivotal Tracker/trello stories?
link to my pivotal tracker :-https://trello.com/c/gY243nQX

**Screenshots (if appropriate)**
N/A
**Questions:**
N/A

2022-05-25 16:47 UTC, shemalucien requested changes
Can you use icons for  edit, save, and delete buttons to maintain the consistency of the design

2022-05-27 10:47 UTC, songa1 reviewed
Check out on your merge history and see unfinished one.

2022-05-27 10:47 UTC, songa1 commented on src/tests/landingpage.test.js
> +<<<<<<< HEAD
Check out this. It might be unfinished merge.

2022-05-27 10:47 UTC, songa1 commented on src/tests/landingpage.test.js
> +>>>>>>> develop
Here too. Check out what's happening!

2022-05-31 11:19 UTC, gyssa-prince requested changes
can you use json db

2022-06-01 18:47 UTC, Rukundo725 approved these changes

2022-06-01 18:47 UTC, Juleshb approved these changes

2022-06-01 18:48 UTC, Benafrica approved these changes

2022-06-01 19:13 UTC, songa1 approved these changes

2022-06-01 19:13 UTC, merged