Fixing Landing page
atlp-rwanda/phantom-fe-dream-team pull request #39
Opened 2022-05-31 08:37 UTC by Juleshb

What does this PR do?

Fixing Landing page

Description of Task to be completed?

- Remove Register button in the navbar component
- add more information on the landing page (explaining how the app works and polish the responsiveness )
- we can add sliding photos on the homepage
- Improve the responsiveness of how it works
- improve the the contact the component by adding form validations, size of input and text area
- Proofreading on the footer component (Kigali,Rwanda and other mistakes,Location)
- Design the pages of (Terms of services, Privacy Policy,FAQ)
- Remove Contact in the footer 
- Add The links on social media icons that redirects you to the the social media platforms

How should this be manually tested?

Clone the repo

checkout to branch Fix-landing-page-fe

Run npm install to install modules

Run npm run dev:start to start the development server

-route:http://localhost:3000

What are 
<img width="395" alt="Screen Shot 2022-05-31 at 10 33 47" src="https://user-images.githubusercontent.com/93904693/171130257-ab2916cc-de51-49d1-9260-847274efcd6c.png">
![Screen Shot 2022-05-31 at 10 34 27](https://user-images.githubusercontent.com/93904693/171130273-f76d8fa3-3796-499a-9a3d-eca78a4811b5.png)
the relevant Pivotal Tracker/trello stories?
link to my pivotal tracker :-https://trello.com/c/gY243nQX

Screenshots (if appropriate)

2022-05-31 11:14 UTC, gyssa-prince commented
can you remove the register menu on mobile navbar

2022-05-31 18:54 UTC, Rukundo725 approved these changes

2022-05-31 18:54 UTC, Rukundo725 submitted a review, later dismissed

2022-06-01 11:57 UTC, arthurjunior250 approved these changes, later dismissed

2022-06-01 17:34 UTC, shemalucien requested changes
can you tick what you have corrected on the list of the feedback given so that we can know what is remaining to be solved, I can see that some of the feedback given was not corrected.

2022-06-10 07:50 UTC, songa1 approved these changes

2022-06-10 07:51 UTC, shemalucien approved these changes

2022-06-10 12:42 UTC, Rukundo725 approved these changes

2022-06-10 15:51 UTC, merged